config/routes.rb
ACMApp::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar,
  :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "event_calendar/index"

  get "roster/index"

  resources :orders

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :events

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  get "acm_app/index"
  
  get "users/new"

  root :to => 'acm_app#index', :as => 'acm_app'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
    current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
  acts_as_gmappable
  
  default_scope :order => 'start_at desc'
  
  validates :name, :start_at, :end_at, :location, :description,
      :icon, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :name, :uniqueness => true
  validates :icon, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
  
  def gmaps4rails_address
    address
  end
  def gmaps4rails_infowindow
    "<h4>#{name}</h4>" << "<h4>#{address}</h4>"
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'}

  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
    return true
    else
      errors.add(:base, 'Line Items present')
    return false
    end
  end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
 
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader   :password
  
  validates :address, :presence => true
 
  validates :emailAddress, :presence => true
  
  validates :classification, :presence => true

  validate  :password_must_be_present
  
  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
  
  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  after_destroy :ensure_an_admin_remains

   def ensure_an_admin_remains
     if User.count.zero?
       raise "Can't delete last user"
     end
   end
  
  private

    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end
  
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @admin = is_admin
  end
  
end

app/helpers/acm_app_helper.rb
module AcmAppHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roster_helper.rb
module RosterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% if session[:user_id] %>
	<% if User.find(session[:user_id]).admin = true%>
		<h1>Administration</h1>
		<ol>
			<li>
				<%= link_to 'Products', products_url %>
			</li>
			<li>
				<%= link_to 'Orders', orders_url %>
			</li>
			<li>
				<%= link_to 'Events', events_url %>
			</li>
			<li>
				<%= link_to 'Users', users_url %>
			</li>
		</ol>
	<% else %>
		<h1>Not Authorized</h1>
	<% end %>
<% else %>
	<h1>Not Authorized</h1>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VSU ACM</title>
		<!-- START:stylesheet -->
		<%= stylesheet_link_tag :all %> <!-- END:stylesheet -->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body id="store">
		<div id="banner">
			<!-- <%= image_tag("logo.png") %> -->
			<%= @page_title || "VSU ACM" %>
		</div>
		<div id="columns">
			<div id="side">
				<%= link_to 'Home', acm_app_index_path %>
				<br />
				<a href="http://www.acm.org">National ACM</a>
				<br />
				<!--<a href="http://www..../faq">Questions</a><br />

				<a href="http://www..../news">News</a><br />
				<a href="http://www..../contact">Contact</a><br /> -->
				<% if !session[:cart_id].nil? %>
				<%= link_to "My Shopping Cart", cart_path(session[:cart_id]) %>
				<% else %>
				My Shopping Cart
				<% end %>
				<% if session[:user_id] %>
				<br />
				<%= link_to 'Orders', orders_path %>
				<br />
				<%= link_to 'Products', products_path %>
				<br />
				<%= link_to 'Users', users_path %>
				<br />
				<%= link_to 'Events', events_path %>
				<br />
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
				<br />
			</div>
			<div id="main">
				<%= yield %><!-- <label id="code.depot.e.include"/> -->
			</div>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VSU ACM</title>
		<!-- START:stylesheet -->
		<%= stylesheet_link_tag "two" %> <!-- END:stylesheet -->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
		<%= yield :head %>
	</head>
	<div id="container">
		<div id="header">
			<h1> <%= @page_title || "VSU ACM" %> </h1>
		</div>
		<div id="navigation">
			<ul>
				<li>
					<%= link_to 'Home', acm_app_url %>
				</li>
				<li>
					<%= link_to 'Store', store_index_path %>
				</li>
				<li>
					<%= link_to 'Events', calendar_path %>
				</li>
				<li>
					<%= link_to 'Roster', roster_index_path %>
				</li>
				<% if session[:user_id] %>
					<% if @admin %>
						<li>
							<%= link_to 'Admin', admin_url %>
						</li>
					<% end %>
					<li>
						<%= link_to 'Logout', logout_path, :method => :delete %>
					</li>
				<% else %>
					<li>
						<%= link_to 'Login', login_path %>
					</li>
					<li>
						<%= link_to 'Register', users_new_path %>
					</li>
				<% end %>
			</ul>
		</div>
		<div id="content">
			<%= yield %>
			<%= yield :scripts %>
		</div>
	</div>
	</body>
</html>

app/views/layouts/carts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VSU ACM</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag :all %>
<!-- END:stylesheet -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body id="store">
  <div id="banner">
    <!-- <%= image_tag("logo.png") %> -->
    <%= @page_title || "VSU ACM" %>
  </div>
  <div id="columns">
    <div id="side">
      <%= link_to 'Home', acm_app_index_path %><br />
      <a href="http://www.acm.org">National ACM</a><br />
      <!--<a href="http://www..../faq">Questions</a><br />

      <a href="http://www..../news">News</a><br />
      <a href="http://www..../contact">Contact</a><br /> -->
    </div>
    <div id="main">
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
    </div>
  </div>

</body>
</html>

app/views/layouts/orders.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VSU ACM</title>
		<!-- START:stylesheet -->
		<%= stylesheet_link_tag :all %> <!-- END:stylesheet -->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body id="store">
		<div id="banner">
			<!-- <%= image_tag("logo.png") %> -->
			<%= @page_title || "VSU ACM" %>
		</div>
		<div id="columns">
			<div id="side">
				<%= link_to 'Home', acm_app_index_path %>
				<br />
				<a href="http://www.acm.org">National ACM</a>
				<br />
				<!--<a href="http://www..../faq">Questions</a><br />

				<a href="http://www..../news">News</a><br />
				<a href="http://www..../contact">Contact</a><br /> -->
				<% if !session[:cart_id].nil? %>
				<%= link_to "My Shopping Cart", cart_path(session[:cart_id]) %>
				<% else %>
				My Shopping Cart
				<% end %>
				<% if session[:user_id] %>
				<br />
				<%= link_to 'Orders', orders_path %>
				<br />
				<%= link_to 'Products', products_path %>
				<br />
				<%= link_to 'Users', users_path %>
				<br />
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
				<br />
			</div>
			<div id="main">
				<%= yield %><!-- <label id="code.depot.e.include"/> -->
			</div>
		</div>
	</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VSU ACM</title>
		<!-- START:stylesheet -->
		<%= stylesheet_link_tag :all %> <!-- END:stylesheet -->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body id="store">
		<div id="banner">
			<!-- <%= image_tag("logo.png") %> -->
			<%= @page_title || "VSU ACM" %>
		</div>
		<div id="columns">
			<div id="side">
				<%= link_to 'Home', acm_app_index_path %>
				<br />
				<a href="http://www.acm.org">National ACM</a>
				<br />
				<!--<a href="http://www..../faq">Questions</a><br />

				<a href="http://www..../news">News</a><br />
				<a href="http://www..../contact">Contact</a><br /> -->
				<% if !session[:cart_id].nil? %>
				<%= link_to "My Shopping Cart", cart_path(session[:cart_id]) %>
				<% else %>
				My Shopping Cart
				<% end %>
				<% if session[:user_id] %>
				<br />
				<%= link_to 'Orders', orders_path %>
				<br />
				<%= link_to 'Products', products_path %>
				<br />
				<%= link_to 'Users', users_path %>
				<br />
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
				<br />
			</div>
			<div id="main">
				<%= yield %><!-- <label id="code.depot.e.include"/> -->
			</div>
		</div>
	</body>
</html>

app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VSU ACM</title>
		<!-- START:stylesheet -->
		<%= stylesheet_link_tag "two" %> <!-- END:stylesheet -->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="container">
			<div id="header">
				<h1> <%= @page_title || "VSU ACM" %> </h1>
			</div>
			<div id="navigation">
				<ul>
				<li>
					<%= link_to 'Home', acm_app_url %>
				</li>
				<li>
					<%= link_to 'Store', store_index_path %>
				</li>
				<li>
					<%= link_to 'Events', calendar_path %>
				</li>
				<li>
					<%= link_to 'Roster', roster_index_path %>
				</li>
				<% if session[:user_id] %>
					<% if @admin %>
						<li>
							<%= link_to 'Admin', admin_url %>
						</li>
					<% end %>
					<li>
						<%= link_to 'Logout', logout_path, :method => :delete %>
					</li>
				<% else %>
					<li>
						<%= link_to 'Login', login_path %>
					</li>
					<li>
						<%= link_to 'Register', users_new_path %>
					</li>
				<% end %>
				</ul>
			</div>
			<div id="content-container">
				<div id="content">
					<%= yield %>
				</div>
				<%= hidden_div_if(@cart.line_items.empty?, :id => "aside") do %>
					<%= render @cart %>
				<% end %>
			</div>
	</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>VSU ACM</title>
		<!-- START:stylesheet -->
		<%= stylesheet_link_tag :all %> <!-- END:stylesheet -->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body id="store">
		<div id="banner">
			<!-- <%= image_tag("logo.png") %> -->
			<%= @page_title || "VSU ACM" %>
		</div>
		<div id="columns">
			<div id="side">
				<%= link_to 'Home', acm_app_index_path %>
				<br />
				<a href="http://www.acm.org">National ACM</a>
				<br />
				<!--<a href="http://www..../faq">Questions</a><br />

				<a href="http://www..../news">News</a><br />
				<a href="http://www..../contact">Contact</a><br /> -->
				<% if !session[:cart_id].nil? %>
				<%= link_to "My Shopping Cart", cart_path(session[:cart_id]) %>
				<% else %>
				My Shopping Cart
				<% end %>
				<% if session[:user_id] %>
				<br />
				<%= link_to 'Orders', orders_path %>
				<br />
				<%= link_to 'Products', products_path %>
				<br />
				<%= link_to 'Users', users_path %>
				<br />
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
				<br />
			</div>
			<div id="main">
				<%= yield %><!-- <label id="code.depot.e.include"/> -->
			</div>
		</div>
	</body>
</html>